[theme]
base = "dark"
primaryColor="#7c6af7"
font="pretendard"
backgroundColor="#181818"
secondaryBackgroundColor="rgba(09, 09, 09, 0.25)"

[theme.sidebar]
backgroundColor="#000000"

[server]
# port = 8080
maxMessageSize = 3000
maxUploadSize = 3000
enableXsrfProtection = false
enableCORS = false